// -*- tab-width:4; c-basic-offset:4; -*-

'use strict';

let x = 0, y = 0;

let atoms = {};
let bonds = {};

let id = 0;

function addBond(dx, dy) {
	const source = getCurrentAtom();
	x += dx;
	y += dy;
	const dest = getCurrentAtom();
	const b = getBond(source, dest);
	console.log(getMolecule());
}

function getCurrentAtom() {
	const key = x + ',' + y;
	let res;
	if (key in atoms)
		res = atoms[key];
	else {
		res = { id: id++, x: x, y: y };
		atoms[key] = res;
	}
	return res;
}

function getBond(a1, a2) {
	if (a1.id < a2.id) {
		const tmp = a1;
		a1 = a2;
		a2 = tmp;
	}
	let key = a1.id + '-' + a2.id;
	let res;
	if (key in bonds)
		res = bonds[key];
	else {
		res = { id: id++, a1: a1.id, a2: a2.id };
		bonds[key] = res;
	}
	return res;
}

function getMolecule() {
	console.log(atoms);
	let atomIDs = '';
	let elementTypes = '';
	let bondArray = '';

	for (const id in atoms) {
		atomIDs += atoms[id].id + ' ';
	}

	for (const id in bonds) {
		const b = bonds[id];
		bondArray += `<bond id="${b.id}" atomRefs2="${b.a1} ${b.a2}" order="1"/>\n`;
	}
	
	let mol = `<?xml version="1.0" encoding="UTF-8"?>
<cml xmlns="http://www.chemaxon.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.chemaxon.com/marvin/schema/mrvSchema_16_02_15.xsd" version="ChemAxon file format v16.02.15, generated by v18.4.0">
<MDocument>
  <MChemicalStruct>
    <molecule molID="m1">
      <atomArray atomID="${atomIDs}" elementType="${elementTypes}"/>
      <bondArray>
${bondArray}
      </bondArray>
    </molecule>
  </MChemicalStruct>
</MDocument>
</cml>`;

	return mol;
}
